### ISSUE TITLE
`compose` and `pipe` should respect the interface of the head functions

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#11]
While it is great and all that the head functions can match the ary-ity of the head functions, it should also match the calling interface. If that head function is curried, than the resulting function from `pipe` or `compose` should also be curried.

**Comment by galileopy** [comment]
Maybe all functions should be curried, since curry let's you call partially or fully. And might be easier to implement.

**Comment by evilsoft** [comment]
No reason to do this.
As I go through all possible implementations, I find more and more that this behavior is very edge case-y.
Do not think we should pursue this. We can reopen if it is requested by a user.
