### ISSUE TITLE
Are they `helpers` or `funcs`?

### ISSUE THREAD

**Issue by flintinatux** [evilsoft/crocks#12]
It seems that what the docs call "Helper functions" are exposed under `require('crocks').helpers`, but stored in `crocks/funcs`, which I didn't expect.  For example, if I went looking for `require('crocks/funcs/compose')`, it wouldn't be at `require('crocks').helpers.compose`

For reference:
https://github.com/evilsoft/crocks/blob/master/crocks.js#L28-L30

**Comment by flintinatux** [comment]
Wow, I'm a super bad code reader.  Please disregard this issue.  `compose` is exposed directly, as in:
```js
const { compose } = require('crocks')
```
Which is what I would have wanted anyways.  😄

**Comment by evilsoft** [comment]
I think you have a good point there. Gonna reopen this for all those code readers out there. 
funcs is a horrible name for these, going to go with something like utility or helpers. Probs `utility`.

Good catch. naming is super hard!!

**Comment by evilsoft** [comment]
Submitted [PR#24](https://github.com/evilsoft/crocks/pull/24) to address this.

**Comment by evilsoft** [comment]
Merged [PR#24](https://github.com/evilsoft/crocks/pull/24).
Closing.
