### ISSUE TITLE
Async broken - Uncaught ReferenceError: isFunction is not defined

### ISSUE THREAD

**Issue by flintinatux** [evilsoft/crocks#120]
I don't have any trouble bundling with `browserify`, but if I bundle with `wepback` using es6 `import` syntax like this:
```js
import Async from 'crocks/crocks/Async'
```
then I get this error in the browser:
```
Uncaught ReferenceError: isFunction is not defined
    at curry (curry.js:15)
    at eval (isSameType.js:37)
    at Object.<anonymous> (authoring.bundle.js:11045)
    at __webpack_require__ (authoring.bundle.js:556)
    at fn (authoring.bundle.js:87)
    at eval (Async.js:10)
    at Object.<anonymous> (authoring.bundle.js:10991)
    at __webpack_require__ (authoring.bundle.js:556)
    at fn (authoring.bundle.js:87)
    at Object.eval (socketCollabs.js:9)
```
I can clearly see in the `curry.js` file that `isFunction` is _very_ defined, so I'm thinking it might be something in your dependency tree that is confusing poor `webpack`.  Happy to help duplicate the error for you when you get a chance.  In the meantime, I've fallen back to `Promise`, which is not a good match for redux action creators, but it'll do until we get `Async` working.

**Comment by evilsoft** [comment]
Goof find. I think I know what is going on. Will get on this.

**Comment by evilsoft** [comment]
@flintinatux hmm. the thing I thought is was is not giving me issue. I am having a hard time repro-ing.
Would it be possible to get some more information? Like:
* version of webpack.
* your js/jsx rule defs.
* maybe some code around where you are seeing this silly thing trigger.

**Comment by flintinatux** [comment]
Try it in `rise-frontend#master`.  Just import it into any file, and you should get the same result.

**Comment by evilsoft** [comment]
Looks like this is resolved.
Closing.
