### ISSUE TITLE
"returing" – typo or on purpose?

### ISSUE THREAD

**Issue by rpearce** [evilsoft/crocks#177]
I've noticed a lot of errors using the word `returing` when I reckon it should be `returning`. Here is a search that returns ~50 results:

https://github.com/evilsoft/crocks/search?utf8=%E2%9C%93&q=returing&type=

Glad to fix it up myself but wanted to check first.

**Comment by evilsoft** [comment]
Totes Typo!
I would absolutely ❤️ a PR. Thank you :sire:
