### ISSUE TITLE
babel-plugin-crocks

### ISSUE THREAD

**Issue by rpearce** [evilsoft/crocks#189]
In the same vein as https://github.com/lodash/babel-plugin-lodash and https://github.com/megawac/babel-plugin-ramda, I have two questions:

* has anyone done this?
* mind if I do it?

**Comment by evilsoft** [comment]
No and yes

**Comment by dalefrancis88** [comment]
This seems pretty succinct, should we close the issue? @evilsoft

**Comment by rpearce** [comment]
@dalefrancis88 I got married and haven't had any time to even think about this! Works for me, unless @evilsoft wants to keep it open for someone else to take a crack at.

**Comment by dalefrancis88** [comment]
@evilsoft should we close this?

**Comment by rpearce** [comment]
I'll close it, but IMO it (or something like it) should be done eventually
