### ISSUE TITLE
Add flatting examples to natural transformation examples

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#203]
When looking over the docs we already have, noticed that the Natural Transformation Examples do not show flattening. Basically they should provide something like this:
```js
const { Nothing, Just } = require('crocks/Maybe')

const { Left, Right } = require('crocks/Either')

const eitherToMaybe = require('crocks/Maybe/eitherToMaybe')

Just(Right(34))
  .chain(eitherToMaybe)
// Just 34

Just(Left(false))
  .chain(eitherToMaybe)
// Nothing
```

**Comment by dalefrancis88** [comment]
To update the currently live documentation the following need to be done:

[ ] Async
[ ] Either
[ ] Maybe
[ ] Pair
[ ] First
[ ] Last

**Comment by dalefrancis88** [comment]
First and last not valid because they don't have a `chain` method

**Comment by dalefrancis88** [comment]
Going to close this issue off, @evilsoft we can re-open if you feel there is still more to do
