### ISSUE TITLE
Add `propEq` and `propPathEq` to predicates

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#205]
These are a pair of handy predicates that should be included in the library. 

They should have the following signatures:
* `propEq :: String -> a -> Object -> Boolean`
* `propPathEq :: [ String ] -> a -> Object -> Boolean`
 
Both should return false if the key does not exist. and should throw in the case of String (or [ String ]) or Object not being the proper types. Under the hood `src/core/equals.js` should be used for equality by value.

The following needs to be accomplished:
* Add code, each function in its own file.
  - [ ] `src/predicates/propEq.js`
  - [ ] `src/predicates/propPathEq.js`
* One spec file per function (`src/predicates`)
  - [ ] `src/predicates/propEq.spec.js`
  - [ ] `src/predicates/propPathEq.spec.js`
* Documentation (`/src/pages/docs/functions/predicate-functions.md`)
  - [ ] Entry for` propEq`
  - [ ] Entry for` propPathEq`
* Expose new functions to public API (`src/index.js`, in predicates section)
  - [ ] Entry for` propEq`
  - [ ] Entry for` propPathEq`
* Add specs for new public functions (`src/index.spec.js`)
  - [ ] Entry for` propEq`
  - [ ] Entry for` propPathEq`

**Comment by karthikiyengar** [comment]
For reasons of consistency, should it be `propEq :: (String | Number) -> a -> Object -> Boolean`, similar to `hasProp`

**Comment by evilsoft** [comment]
Yeppers!! You got it!

**Comment by karthikiyengar** [comment]
A few quick questions about `propPathEq`
1. I'm planning to use the already implemented `propPath` for this one, but it's not a part of `src/core`. Thoughts?
2. Since `propPath` returns a `Maybe`, should we also do an unboxed equality check? In other words, should `propPathEq(["some", "key"], 5, { some: { key: 5 } })` be true?

**Comment by evilsoft** [comment]
This has been merged.
Closing!!
