### ISSUE TITLE
Add `find` function to `Maybe` namespace

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#206]
A `Maybe` returning `find` would be an excellent addition to the lib. So lets add one to `src/Maybe/find.js` that has the following signature:

`find :: Foldable f => ((a -> Boolean) | Pred) -> f a -> Maybe a`

The following needs to be accomplished:
* Add code:
  - [x] `src/Maybe/find.js`
* Add specs
  - [x] `src/Maybe/find.spec.js`
* Documentation
  - [x] Update ReadMe (`src/Maybe/README.md`)
  - [x] Add to Docs with description and example usage (`docs/src/pages/docs/crocks/Maybe.md`)
  - [x] Add link to Helpers Section (`docs/src/pages/docs/functions/index.md`)
* Expose new functions to public API (`src/index.js`)
  - [x] Entry for` find`
* Add specs for new public functions (`src/index.spec.js`)
  - [x] Entry for` find`

**Comment by bennypowers** [comment]
I'm (tentatively) interested in trying out this implementation, if no one else has a stake in it.

**Comment by dalefrancis88** [comment]
Go for it, I was going to give it a crack but I won't get to it till the weekend

**Comment by dalefrancis88** [comment]
Lol I should say, no issues from me, not "go for it" :)

**Comment by evilsoft** [comment]
This has been addressed and will go out with release: 0.9.1
