### ISSUE TITLE
Fix up "Highlights" on the main page of docs

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#208]
There is only like (1) thing on that list that says why to use crocks. Would like to have some copy that addresses the following points:

* One library with no dependencies to manage for the common ADTs, no need to wait for updates to trickle through the FP community. All updates happen across all types at the same time, making upgrading a breeze.
* A common interface between types, no need to remember how one type does an operation versus another from a different library.
* Helpful Error messaging at the point where there was a problem, not deep down in the depths of some abstraction in `crocks`.
* A slew of helper functions, predicates and combinators to easily build out common operations when working with ADTs

**Comment by dalefrancis88** [comment]
Going to close this issue off, @evilsoft we can re-open if you feel there is still more to do
