### ISSUE TITLE
Docs should prefer import over require

### ISSUE THREAD

**Issue by bennypowers** [evilsoft/crocks#228]
This issue humbly suggests that all docs prefer the standard `import` form over calls to CommonJS-style `require()`. 

While it's true that, as a community, we must support legacy `require` for the next few years (until node LTS supports `import` without flags), nonetheless, library authors should already document according to the standard.

This issue *does not* recommend removing `require`-based examples from the main README.md, as many (most?) Users still require (zing!) old-school modules. Rather, the examples in each Crock/Monoid/Function/foo's documentation should be written primarily according to the standard.

If this suggestion finds favour in your eyes, I'd be happy to submit a pull request.

**Comment by evilsoft** [comment]
I will need to start working on [this](https://github.com/evilsoft/crocks/issues/146) and have it done before your docs get worked in.

I have a couple ways to back-compat so people using the flags will work as well as people using the require statements. So I will bump up priority  on that and tackle this next. I agree 💯 with this issue and now is a better time than later!

So go for it if you wanna. I will make sure that the other bits are done so no users will be impacted no matter their style, babel, require or flagged

**Comment by evilsoft** [comment]
Okay, so it looks like the best way to document them is to always import the default and then destructure off of the resulting default. Basically:
```js
// this
import Maybe from 'crocks/Maybe'
const { Nothing, Just } = Maybe

// and not this
import { Nothing, Just } from 'crocks/Maybe'
```

When better `commonjs` -> `msj` hooks are better and they hit LTS, we will update the docs and the code to allow the second case. As that will be the preferred target. So the constructor will export on the default and each of the construction helpers can come in on separate exports.
