### ISSUE TITLE
Helping

### ISSUE THREAD

**Issue by dalefrancis88** [evilsoft/crocks#231]
Hey, is there anything i can do to help/contribute to this? 

I havn't found any bugs yet in what i've been building but would love to learn more about the library by contributing

**Comment by evilsoft** [comment]
Heck yeah. I would recommend hoping in the gitter channel [here](https://gitter.im/crocksjs/crocks) and just start playing with the lib getting to know it. Right now we are on a big push to start integrating with all the other libs out there, the fantasy-land spec, Sanctuary and Ramda. Also there is a parallel push for back filling documentation.

I am planning on putting a road map together for 1.x and will have that soon when caught up on fixing some horrible mistakes and assumptions that were made when this library was starting to be built.

As it sounds like you are a user of the lib just hanging out in the room and helping people that come in is another amazing way to support the project (it if gets you added to the Contributors list at the bottom of the README!) But from there you may get the general feel and find a niche to land in.

**Comment by evilsoft** [comment]
Also I am trying harder to make sure that as I find things I add them to the issues list. That way if something pops in that catches your 👁 just grab it and give it a shot. If you have any questions about patterns, or the lib or anything really, that gitter is going to be the best place.

**Comment by evilsoft** [comment]
And most importantly...Thank you so much for offering to help with this!!

**Comment by dalefrancis88** [comment]
Awesome. Sounds good. I am currently working with React/Redux and using Crocks to create a composable state selector. 
With Redux you have a large state object that you pull from into your containers and it's generally a good pattern to have those selectors out of the logic of the containers so using crocks i've made a pattern that makes creating those selectors really easy. Could be something nice to add to the library or as a contrib.

Also I wouldnt mind adding a few small things to make importing in es6 a little easier, happy to create a pull request for that if you're open to it

**Comment by dalefrancis88** [comment]
Also will now go join the Gitter chanel
