### ISSUE TITLE
Report Proper Function Name on Error

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#234]
Now that we are moving to FL integration through the use of pointfree and helper functions, we need a way to signal to the user the path in which the error occurred. If using the FL methods, it should be reported as such.

That means if an error occurred using the "public" or "fluent" version of the function it should read:
`Either.map: Function required`

But if using the FL method, typically through a helper/pointfree function, the error should read:
`Either.fantasy-land/map: Function required`

This will require that the type functions that have FL equivalents must be partial applied with the name that will be in the method name space:
`[Type].[methodName]: Error Message`

**Comment by dalefrancis88** [comment]
@bennypowers are you still looking for something? what about this?

**Comment by evilsoft** [comment]
This shipped. Closing
