### ISSUE TITLE
Search on Documentation is not working correctly

### ISSUE THREAD

**Issue by HenriqueLimas** [evilsoft/crocks#254]
The search for documentation is not returning nice results. Trying to search for `assoc` for example, it doesn't return the correct place of the documentation for `assoc`. Another example is searching for `Maybe`, it should return the `Maybe` documentation.

**Comment by evilsoft** [comment]
[PR](https://github.com/evilsoft/crocks/pull/255) was merged....keeping this open to track the by function name portion

**Comment by evilsoft** [comment]
Actually going to close this for now. we can revisit when you start getting reports
