### ISSUE TITLE
Document equals property for all Monoids

### ISSUE THREAD

**Issue by karthikiyengar** [evilsoft/crocks#259]
Since monoids support equality checks by virtue of #230, this feature needs to be documented

- [x] Add equals section to docs pages
  - [x]  [docs/All](https://github.com/evilsoft/crocks/blob/master/docs/src/pages/docs/monoids/All.md)
  - [x]  [docs/Any](https://github.com/evilsoft/crocks/blob/master/docs/src/pages/docs/monoids/Any.md)
  - [x]  [docs/Assign](https://github.com/evilsoft/crocks/blob/master/docs/src/pages/docs/monoids/Assign.md)
  - [x]  [docs/First](https://github.com/evilsoft/crocks/blob/master/docs/src/pages/docs/monoids/First.md)
  - [x]  [docs/Last](https://github.com/evilsoft/crocks/blob/master/docs/src/pages/docs/monoids/Last.md)
  - [x]  [docs/Max](https://github.com/evilsoft/crocks/blob/master/docs/src/pages/docs/monoids/Max.md)
  - [x]  [docs/Min](https://github.com/evilsoft/crocks/blob/master/docs/src/pages/docs/monoids/Min.md)
  - [x]  [docs/Prod](https://github.com/evilsoft/crocks/blob/master/docs/src/pages/docs/monoids/Prod.md)
  - [x]  [docs/Sum](https://github.com/evilsoft/crocks/blob/master/docs/src/pages/docs/monoids/Sum.md)
- [x] Add equals section to README pages
  - [x]  [readme/All](https://github.com/evilsoft/crocks/blob/master/src/All/README.md)
  - [x]  [readme/Any](https://github.com/evilsoft/crocks/blob/master/src/All/README.md)
  - [x]  [readme/Assign](https://github.com/evilsoft/crocks/blob/master/src/Assign/README.md)
  - [x]  [readme/First](https://github.com/evilsoft/crocks/blob/master/src/First/README.md)
  - [x]  [readme/Last](https://github.com/evilsoft/crocks/blob/master/src/Last/README.md)
  - [x]  [readme/Max](https://github.com/evilsoft/crocks/blob/master/src/Max/README.md)
  - [x]  [readme/Min](https://github.com/evilsoft/crocks/blob/master/src/Min/README.md)
  - [x]  [readme/Prod](https://github.com/evilsoft/crocks/blob/master/src/Prod/README.md)
  - [x]  [readme/Sum](https://github.com/evilsoft/crocks/blob/master/src/Sum/README.md)
- [ ] Add links to [docs/pointfree]

**Comment by karthikiyengar** [comment]
@evilsoft - I'm not sure about `Add links to [docs/pointfree]`. Is there anything specific that we need to add here?

**Comment by evilsoft** [comment]
This has been shipped. Close
