### ISSUE TITLE
Any place to talk about crocks?

### ISSUE THREAD

**Issue by ggerico** [evilsoft/crocks#272]
I would like to discuss the code that I wrote using crocks, Is there any 'official' place for that purpose?
Something like a reddit? 
Tks,
Germain.

**Comment by evilsoft** [comment]
Sorry it took so long to respond. I had a response but did not submit it.
We do have a gitter which you can find here:
https://gitter.im/crocksjs/crocks

Just a chat room, nothing like a reddit.

**Comment by evilsoft** [comment]
Okay. having a reddit makes sense. Good Call. I have created one:
https://www.reddit.com/r/crocksjs/

(this can be used to showcase/discuss code in a forum format as opposed to a some chat that information ends up being repeated again and again)

**Comment by evilsoft** [comment]
closing.
