### ISSUE TITLE
Partial helper unclear behaviour

### ISSUE THREAD

**Issue by cristian-gabbanini** [evilsoft/crocks#288]
I'm using the partial helper as below to wrap an Async:
```javascript
const fs = require("fs");
const partial = require("crocks/helpers/partial");
const { appendFile } = fs;
const appendAsync = partial(Async.fromNode(appendFile));
const writeLogAsync = appendAsync("program.log");
```
I'd expect **writeLogAsync** to be a Function that, when provided with some other arguments would return an Async Function. 
But writeLogAsync is already an Async Function.
I'm not sure if it's my bad or not...I'd though that **partial** should behave like the following, which, by the way, behaves as I would expect:
```javascript
const partial = fn => (...firstArgs) => (...lastArgs) => fn(...firstArgs, ...lastArgs);
```

**Comment by cristian-gabbanini** [comment]
``javascript
partial :: (((*) -> c), *) -> (*) -> c
``
I'm sorry, I should have read the documentation more carefully.
The partial application provided with crocks needs both the function and the first set of arguments at the first invocation while I'd though it required only the function.
Thanks again

**Comment by evilsoft** [comment]
Gonna close this issue out if that is okay with you @cristian-gabbanini 
If not, please let me know and I can reopen it for you!
