### ISSUE TITLE
Should `Monoid(undefined)` return the empty Monoid?

### ISSUE THREAD

**Issue by bennypowers** [evilsoft/crocks#301]
Observe:

```js
const all = All(undefined) // All true
const nobody = mreduce(All, []) // true
```
Should monoid constructors return the empty monoid when called with `nil` ?

A practical implication:

```js
isExclusive(undefined) // false
const isAllExclusive = mreduceMap(All, isExclusive)
isAllExclusive([]) // true
```
Users could reasonably expect `allExclusive([])` to be false, since the array has no 'exclusive' members.

In this case, developers will have to do the following, which strikes me as burdensome:
```js
const isAllExclusive = compose(
  option(false),
  map(mreduceMap(All, isExclusive)),
  safe(not(isEmpty))
)
```

**Comment by evilsoft** [comment]
Now you could go the Semigroup route, with `foldMap`, BUT it takes a non-empty list, so you would have to put in a `Maybe` there as well. So you might as well go with `mconcat`

**Comment by evilsoft** [comment]
@dalefrancis88 Been giving this a lot of thought and after careful 🌽sideration, I am 💯 on board with what @bennypowers is saying. I am thinking that this behavior of `Monoid`s should be removed, if `undefined` hits the `Monoid` and it is not expected we should handle it according to the `Monoid`.

In the case of `Any` and `All` which utilize coercion, should coerce into a `false`. All other `Monoid` should throw if their carrier type cannot deal with the unit.

Thoughts?

**Comment by dalefrancis88** [comment]
Sounds good. I'll create a new issue with the details of what needs to be done and reference and collar this issue

**Comment by dalefrancis88** [comment]
Closing as this issue has a resolution and the work will be tracked https://github.com/evilsoft/crocks/issues/371
