### ISSUE TITLE
Add code examples for the `Logic` Functions

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#304]
Add code examples for each of the `Logic` functions on [this page](https://evilsoft.github.io/crocks/docs/functions/logic-functions.html).

The examples should show different ways of using predicate function and the `Pred` type. Also examples with `Either` and `Maybe`  (`safe`, `safeLift`, etc). The combinators should also show their Truth Tables at the top of the example.

### Task List

* [x] And
* [x] ifElse
* [x] implies
* [x] not
* [x] or
* [x] unless
* [x] when

**Comment by dalefrancis88** [comment]
All updates are now in master
