### ISSUE TITLE
Move `project` pointfree function into `Tuple` folder

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#307]
`project` pointfree should live in `Tuple` and also needs to be documented.

* Move `project` to `Tuple` folder
* Make sure it is still accessible from the `crocks` main api.
* Add full documentation to the `Tuple` docs
* Add documentation entry on `Pointfree Functions` page.

**Comment by karthikiyengar** [comment]
@evilsoft - I was checking the existing docs and I do see the documentation for `project`

Additionally, one of the examples for project implies that it also works with a pair:

```
Pair('one', 'two')
  .project(2)
//=> "two"
```

Are we going to implement this? And if so, do we still move `project` around?

**Comment by evilsoft** [comment]
That example is working on a `2-Tuple` named `Pair`.

**Comment by dalefrancis88** [comment]
Closing as this appears to be complete
