### ISSUE TITLE
safe method returning "Just undefined"

### ISSUE THREAD

**Issue by wellyal** [evilsoft/crocks#313]
I'm just testing the library to see if it's going to be useful to me. But I've came up with this output and I'm not sure if is correct. My guess is that the console.log from the code bellow supposed to be `Nothing` but is printing out `Just undefined` is that correct? how come?

```js
import { safe, isNil } from 'crocks'
import { inc } from './utils'

const exercise3 = () => {
  const qs = { pageSize: 10, totalPages: 203 }	
  const page = safe(isNil, qs.page)
  console.log(page) //Just undefined
}
```

**Comment by evilsoft** [comment]
Did you figure it out?
That `safe` is only allowing `undefined`, `null` and `NaN` through (basically all the JS terminal types) what you want is `safe(not(isNil))`

**Comment by evilsoft** [comment]
Hope we pass your tests, if we do not, please let us know how we didn't and we may be able to accommodate or explain why.

**Comment by wellyal** [comment]
> Did you figure it out?
> That `safe` is only allowing `undefined`, `null` and `NaN` through (basically all the JS terminal types) what you want is `safe(not(isNil))`

Yeah, I figure. isNil was returning `true` (as expected) and thats why I end up getting `Just` as the from the safe method.

I didn't know about the not function, I could have just composed a function with not and isNil like this:

```js
const isNotNil = compose(not, isNil)
return safe(isNotNil, x)
```

But what I just used the `prop`function instead and that did the trick for me.

**Comment by wellyal** [comment]
> Hope we pass your tests, if we do not, please let us know how we didn't and we may be able to accommodate or explain why.

I am an elm enthusiastic and this repo is really similar. So I really liked what I've seen so far.

**Comment by evilsoft** [comment]
Well the `not` function takes a predicate function, not a value, so that compose would not have worked as expected. all of the [logic functions](https://evilsoft.github.io/crocks/docs/functions/logic-functions.html) take either a predicate `a -> Boolean` or a [`Pred`](https://evilsoft.github.io/crocks/docs/crocks/Pred.html) datatype. You can consider them logic combinators in a way.

**Comment by evilsoft** [comment]
Well the functions `implies`, `not` `or` and `and` as logic combinators.
