### ISSUE TITLE
['fantasy-land/ap'] does not exist on Async

### ISSUE THREAD

**Issue by pfgray** [evilsoft/crocks#314]
The `fantasy-land/ap` key doesn't exist on `Async` values. I don't see it [here](https://github.com/evilsoft/crocks/blob/master/src/core/flNames.js#L4), so I don't think the other applicatives have it, either. Is this intentional, or just a small oversight?

I can work on a PR that adds them if you want!

**Comment by karthikiyengar** [comment]
Hi @pfgray - thanks for the issue.

We currently implement applicatives in a way that's different from the fantasy-land specification, and thus we cannot expose the key at the moment.

The fantasy-land implementation is tracked in https://github.com/evilsoft/crocks/issues/209 and the key would be added once that ticket is implemented.

**Comment by pfgray** [comment]
Ah, I see! I'll go ahead and track this as part of that ticket, thanks!

**Comment by evilsoft** [comment]
@pfgray the other FL that is not implemented is `fantasy-land/traverse` because of its relationship with `Applicative`
