### ISSUE TITLE
Lookig for a way to sequence an object of monads to a monad of object

### ISSUE THREAD

**Issue by diegovdc** [evilsoft/crocks#319]
Like traverse or sequence for an array of a monad, but for an object.

i.e. `{k1 : Maybe a, k2: Maybe b ...} -> Maybe {k1: a, k2: b, ...}`

Is there anything like this for crocks?

**Comment by diegovdc** [comment]
Thanks,

so I have calcualtions like this:
```js
const calculations = {
  someCalculation: safeDiv(x, y), // :: Maybe Float
  someCalculation2: safeDiv(x2, y2), // :: Maybe Float
  someCalculation3: safeDiv(x3, y3), // :: Maybe Float
}
```

and currently I am doing this to sequence my operation: 

```js
const sequenceObj = (monadOf) => R.pipe( // this seems kind of inefficient though
  R.toPairs,
  R.map(R.pipe(
    R.over(R.lensIndex(0), monadOf),
    R.sequence(monadOf)
  )),
  R.sequence(monadOf),
  R.map(R.fromPairs),
)
```

A good deal of why I need this is to preserve the name of the keys in the calculation.  It is also worth mentioning, that this is happening in a `chain` for another `Maybe` ( which owns the data :`{x, y, x1, y1, ...}`, and to which the results should be added),  so that is why I want to sequence the object, so that I end up with only one Maybe, and can be sure that the whole data stucture is consistent, if the calculations went ok.

As a sidenote I have also found my self validating form data in pretty much te same way, so that is why I am also interested in this pattern.

**Comment by dalefrancis88** [comment]
Going to close this, feel free to re-open if there is any further need for discussion :)
