### ISSUE TITLE
Have all `compose`/`pipe` functions return only unary functions

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#338]
### Description/Location

**location:** './helpers/aThing.js'
**description:**
The current implementation allows the ability to apply any number of arguments to the head function in the composition/pipe. While this is very :corn:venient at times, it has been know to lead to hard to reason about compositions and many time unnecessary  argument juggling. It also provides limits on how a composed function is curried.

By limiting this to just a unary function, it removes the ability to get into a juggling mess and can also allow us to properly curry the function that is returned for cases like:

```js
// pluck :: String -> [ a ] -> Maybe b
const pluck = curry(
  key => map(prop(key))
)

pluck('id', [ { id: 2 } ])
//=> [ Just 2 ]
```

becomes:
```js
// pluck :: String -> [ a ] -> Maybe b
const pluck = 
 compose(map, prop)
```
While is maybe different then what we are used to from the standard in JS in most libs, if you look at the code and remember that `x => f(g(x))` is the same thing as `compose(f, g)` see how these are actually equivalent. Now people who for some reason have not adopted compose and STILL use pipe for one reason or another, it may be harder for this to click when writing and maintaining code. But as shown above, these are equivalent and should be allowed to be implemented that way.

This is more of a proposal to get peoples opinions and thoughts. Would love to get some emoji reactions to this, and if possible a comment on why you feel the way you do.

### Task List

* [ ] Build out a task list if enough people understand why and the implications.

For more information, see the `CONTRIBUTING` guide.

**Comment by dalefrancis88** [comment]
I think to help with upgrading and reducing the pain a little, could we keep the previous implementation with some other name? we could have a `composeN` that takes the number of initial arguments to pass in, then the rest get fed as normal. So if people want to keep there behaviour it won't require a large refactor because it's highly likely people have done a lot of args juggling

Signature (this sucks, i don't know these sigs well)
`composeN :: n -> [fns] -> * -> * -> a`

**Comment by karthikiyengar** [comment]
@dalefrancis88 - I don't think that this change would affect the people that have done args juggling as it's only enforcing that the head to be unary. 

However, it does get in the way of some other use cases. A contrived example follows:

```javascript
 compose(ap(Maybe.of(10)), Maybe.of, add)(5)
//=> Just 15 (current implementation)
```
Our new implementation however, would result in an exception. 

Personally, I dig the simplification, but I am not sure if I completely understand how it still remains lawful. Could you please elaborate @evilsoft? 

I am a bit concerned that by changing the behaviour of `compose`, we might break large codebases, especially the ones without test coverage. Also, `compose` is bread and butter for any FP library and a lot of programmers would expect Ramda et al.'s behaviour. That said, we could consider exposing it under a different name. I see that Sanctuary used to have a similar implementation called `S.meld` https://github.com/sanctuary-js/sanctuary/pull/280/files
 
Also, I'm curious to hear your thoughts on preserving the same behaviour for all functions in the compose chain (not only head)? 
```javascript
supercompose(Pair, map, prop)('id', [{ id: 5}], 10)
//=> Pair(Just 5, 10)
```

**Comment by rpearce** [comment]
I am :100: for this functionality, and I don't know where I stand yet on the naming. This is how I always wanted/expected `compose` to work. Having some way for what worked before to keep working would be sweet for existing users, though... however that happens.

**Comment by dalefrancis88** [comment]
hey @rpearce and @evilsoft I had a thought on how to make this work and created a PR for discussion

https://github.com/evilsoft/crocks/pull/422

**Comment by dalefrancis88** [comment]
@evilsoft @karthikiyengar  knowing that we can `curry` the `composition` and we also have `compose2` now to get this to work, do we still want this as an addressable issue given that this would be a quite serious breaking change were we to implement it?

**Comment by evilsoft** [comment]
Nah. I think we are good on closing this.
