### ISSUE TITLE
Test for monoid empty values in `isEmpty`

### ISSUE THREAD

**Issue by jasminabasurita** [evilsoft/crocks#355]
Currently passing an empty from any monoid to `isEmpty` returns false. I think it would make sense if `isEmpty` included tests for empty monoids 

###### Example:
```js
//current
isEmpty(Min.empty()) // => false
//desired
isEmpty(Min.empty()) // => true
```

**Comment by dalefrancis88** [comment]
I really like this idea. How were thinking it'd best be implemented with being able to detect that it is an `empty` of a particular monoid?

**Comment by karthikiyengar** [comment]
This would be great! Would we also be including zero (https://github.com/fantasyland/fantasy-land#plus) in this check? This would mean that `isEmpty(Maybe.zero())` would be true.

**Comment by dalefrancis88** [comment]
I am not sure we should consider `zero` an `empty` value if we start to do that, we're a step away from considering `Nothing` an `empty` value. I think `zero` itself holds an intrinsic value above that of something that is `empty`

**Comment by jasminabasurita** [comment]
> I really like this idea. How were thinking it'd best be implemented with being able to detect that it is an `empty` of a particular monoid?

I was thinking that perhaps the different monoids could include an `isEmpty` function that when invoked would return the expected boolean. Then all we'd need to do within the pointfree `isEmpty` is:
1. check that the function exists and is a function
2. invoke it and return the value

**Comment by dalefrancis88** [comment]
so all monoids values include `empty` as a function, so a `Min(1)` contains a method `empty` and so does a `Min.empty()` do you think there'd be a way to use that to only need to update the `isEmpty` implementation?

**Comment by karthikiyengar** [comment]
What do you think about `isMonoid(x) && equals(x.empty(), x)?`

**Comment by dalefrancis88** [comment]
@jasminabasurita This is now merged into master and will be available in the next release :)
