### ISSUE TITLE
curry modifies functions returned from constant

### ISSUE THREAD

**Issue by goulderb** [evilsoft/crocks#366]
**Describe the bug**
When a constant function is used to return another function, the returned function is automatically curried. This results in the return value no longer matching what was given to constant.

Based on my rough digging, it appears related to the logic of how the curry function works, specifically lines 25-27 in src/core/curry.js. This checks if the value returned by applying the arguments is a function, if it is, it curries the function.

This causes 

**To Reproduce**
```javascript
import { constant } from 'crocks';

// This is not curried, and should be returned unmodified.
const identity = x => x;

const constantOfIdentity = constant(identity);

// Instead, we see that the returned version is now the definition of the curry function.
console.log(constantOfIdentity().toString());

// This returns false, these are no longer reference equivalent.
console.log(constantOfIdentity() === identity);
```

**Expected behavior**
The original value given to constant should be returned unmodified.

**Additional context**
This affects any autocurried crocks function that can wind up returning a function itself. I've seen the same behavior with ifElse and when.

**Comment by goulderb** [comment]
If there are any suggestions as to how this should get resolved, I wouldn't mind tackling it myself. I really love this library on the whole, and this has been the only issue that has thrown me for a loop while using the library.

**Comment by dalefrancis88** [comment]
There could be a way to do it, the question really comes down to what as a global community people would be likely to use this for. 
Honestly i'd never looked at the code for constant till now, i always thought of it as a simple `x => () => x`, which it is, but it looks like for consistencies sake `constant` is being curried. I'm not sure why that is, but it'd be an @evilsoft question.
Personally it's my opinion that constant should always just return exactly what it is is given, this is essentially changing/mapping the value before giving it back.

So two things, the most obvious and simplest way to change this behaviour in the library is to remove `curry` from `constant` however this would then become a breaking change. The second thing is, although this does occur, what's the core of the concern? is it more that the value is changing or is it causing an actual issue?

**Comment by evilsoft** [comment]
It really come down to equivalence vs strict equality.
I am curious why the exact function is needed. the values returned from (esp functions) should be considered equivalent throughout the app, strict equality for things like morphisms (functions) can lead to issues. Have curry in place here gives us a lot of combinatorial power, and I would hate to sacrifice all that power. if you need constant to always return a function that really can be created inside the domain of your use case with just the simple `const K = x => () => x`

**Comment by dalefrancis88** [comment]
I thought it might be something like this, It's interesting because I've never thought to use a function inside of `constant`. Is this a common use case for it?

**Comment by goulderb** [comment]
So, to give a bit of background, the issue that I hit is that I wanted to write some simple ifElse to use as a dispatch function with tcomb's union types. tcomb uses reference equality against the declared "constructor" function for the types. So, the fact that the constructor function becomes curried (it's single arity anyway, so currying it isn't even helpful) causes tcomb to break.

This is actually equally true of any function that winds up returning a function in crocks. So, even without using constant, the following isn't valid going to properly dispatch to the correct tcomb type.

To work around this, I've just switched back to using ramda's ifElse/cond/etc instead since their curry implementation doesn't have this behavior.

Essentially, something like this:
```javascript
import t from 'tcomb';
import { ifElse, constant } from 'crocks';

const A = t.declare('A');

const B = t.declare('B');

const AorB = t.union([A, B]);

AorB.dispatch = ifElse(pred, constant(A), constant(B));
```

**Comment by dalefrancis88** [comment]
I also agree we don't want to lose power for sure, especially if this is a common use. I guess there just lies the management of expectations for the function. When it comes to adding the documentation to `combinators` we should remember to note this

**Comment by goulderb** [comment]
@dalefrancis88 Sure, I can always write it many different ways (the ramda example that I just added to my previous comment, for example, or just arrow functions). It just seems wrong to me that crocks is making assumptions about whether or not it can arbitrarily modify the functions returned from any crocks function. I can see the validity of the points regarding flexibility, but right now this is not even documented behavior. I had to dig to even understand why swapping one ifElse for another changed my code, when I felt they should behave exactly the same based on everything I had read in the documentation.

**Comment by dalefrancis88** [comment]
Well the interesting thing is that you still get the same effect if you switch it out to not use `constant`

`AorB.dispatch = ifElse(hasProp('a'), A, B);`
`AorB.dispatch = ifElse(hasProp('a'), () => A, () => B);`
`AorB.dispatch = ifElse(hasProp('a'), K(A), K(B));`

still all produce false, so i do not think it's `constant` that's causing this

**Comment by goulderb** [comment]
@dalefrancis88 Correct, as I stated in my comment post, it's due to the implementation of curry, specifically lines 25-27. Any function wrapped with curry from crocks will have functions returned from it automatically curried with the crocks curry function as well.

This means any crocks-curried function that returns a function has its value implicitly wrapped in the crocks curry function.

For example:
```javascript
import { curry } from 'crocks';

const identity = curry(val => val);

// This will be the definition of crocks's curry function
console.log(identity(() => 'test').toString());
```

**Comment by dalefrancis88** [comment]
So looking at your second example, if you do nothing but switch out the `ifElse` it switches from `true` to `false`

**Comment by dalefrancis88** [comment]
It's all good man, I get that, just trying to work through the specifics of it and understand how best to solve this to everyones benefit :) The hard this is I don't know this `tcomb` library

**Comment by goulderb** [comment]
@dalefrancis88 No problem, I just wanted to make sure you didn't skim past that part :)

Let me know if there are any other examples I can provide that'd help clarify. I am just using the tcomb example since it's what I encountered this with (I use tcomb with some wrappers to do validation throughout my code base).

**Comment by dalefrancis88** [comment]
All good, thanks for the compliment, it's all @evilsoft :)

Did you see the comment on switching only `ifElse` in the `dispatch` function?

**Comment by goulderb** [comment]
Yes, I did. That's consistent with everything I've seen so far. I have just used Ramda's ifElse/cond for doing the shorthand `dispatch` functions, which I'm happy to continue doing if it makes the most sense for crocks to retain its current curry behavior.

**Comment by evilsoft** [comment]
@goulderb yeah, I was afraid you were going to say tcomb or something to do with specs/tests. It was because of tcomb, that we started adding things like `isSameType` and a lot of the type predicates. I would recommend doing what you have been for now. We have been thinking of ways we can answer this issue of equality vs equivalence  and do not have an answer yet.

But as soon as we do, we will be sure to broadcast it to the world.

**Comment by dalefrancis88** [comment]
Closing this for now as it seems resolved. Feel free to re-open if there is more to discuss
