### ISSUE TITLE
TryCatch should work with curried functions

### ISSUE THREAD

**Issue by dalefrancis88** [evilsoft/crocks#368]
**Is your feature request related to a problem? Please describe.**
Currently pretty much everything we have in the framework easily supports curried functions. By habit most developers curry there functions at there definition, it's been noted that `tryCatch` currently does not allow for curried functions in any form

**Describe the solution you'd like**
It is possible that people manually `curry` there functions or use a different libraries `curry` functions. I understand where this could blow up and cause quite a few problems changing this behaviour, however i feel we could update this function in two parts, first we could look at the number of arguments the func is expecting and pass just those, if any more are available and the return result is a func then lets keep applying. This is similiar to how `curry` works. 

**Describe alternatives for how you do this now**
None that i've found

**Code**
*Example*: https://repl.it/@DaleFrancis/TryCatch-Example
*Proposed*: https://repl.it/@DaleFrancis/TryCatch-Update

**Additional context**
I can see that this is not a straight forward change so I wanted to raise this here and start a discussion

**Comment by zarcode** [comment]
Not sure is it `curry` problem or something else, but I can't easy use `localStorage.getItem` and `localStorage.setItem` functions with tryCatch. So I ended up writing code like this:

```
export const saveAny = (key, state) => compose(
  tryCatch(
    val => localStorage.setItem(...val.toArray())
  ),
  bimap(identity, JSON.stringify),
)(Pair(key, state));

export const loadAny = 
compose(
  either(constant(undefined), identity),
  composeK(
    tryCatch(unary(JSON.parse)),
    tryCatch(x => localStorage.getItem(x))
  )
) 
```

**Comment by dalefrancis88** [comment]
Yeah the way that `tryCatch` is written, it won't work well with the spread operator on the array for args, however just tested this with my proposed updates and it works

**Comment by zarcode** [comment]
Seams proposal is not solving this problem: `tryCatch(localStorage.getItem)` gives `Err TypeError: Illegal invocation`, while `tryCatch(x => localStorage.getItem(x))` works good.

**Comment by evilsoft** [comment]
@zarcode have you tried `bind` on those functions:
```js
tryCatch(localStorage.getItem.bind(localStorage))
```
also by using the [`merge`](https://evilsoft.github.io/crocks/docs/crocks/Pair.html#merge) function you should be able to call a binary function like setItem:
```js
tryCatch(merge(localStorage.setItem.bind(localStorage)))
```
This should help clean up some of it.

**Comment by zarcode** [comment]
Works nice like that, after seeing implementation of `tryCatch` it's clear why ( I could have checked that earlier :/ ). `merge` looks great.

**Comment by dalefrancis88** [comment]
I think the decision was to leave this as is. Closing for now, we can re-open if that changes or i'm wrong
