### ISSUE TITLE
Idea for lens

### ISSUE THREAD

**Issue by r281GQ** [evilsoft/crocks#369]
**Is your feature request related to a problem? Please describe.**

No problem, just a feature.

Hey guys! First of all thanks for the awesome library and the detailed docs. As I was reading through the docs I have not found anything like`lens`. My knowledge limited to the topic, however.

I am using Ramda quite often and I am a big fan of `lens`. Any alternative in this lib or plan to make it as I'd like to use it more often, these ADTs are tasty!!!!

**Describe the solution you'd like**
For me the basic problem is when I need to view/set a certain value on a fairly complicated struct and while digging down I had to `assoc` my way back. With lens that so comfy, I don't have to deal with it.

Some pointFree function with view, set and over settings, to just focus on the given prop.

**Comment by dalefrancis88** [comment]
Hey, welcome! Glad you like the library, it's a lot of fun. All credit to @evilsoft for bring it together :)

Yeah this is definitely on the near roadmap. First we're working through updating and moving a few methods around related to it and trying to get on top of most of the documentation. That being said, i know there are quite a few of us that are wanting this so it may come sooner than you think :)

If you want to take a crack at building it though, we're all open to suggestions, you could submit a PR any time and we can work through it.

**Comment by r281GQ** [comment]
Hey @dalefrancis88, thanks for the reply. So yeah I'll create one! 👍

**Comment by dalefrancis88** [comment]
Nice work. Let me know if you need/want any help with it. There are some changes that were made recently to allow lens to be built pretty easily.
