### ISSUE TITLE
Fix chain example on the Async Docs

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#382]
The `chain` example for `Async` does not work due to the way the `fake` function is implemented. Should be a Kleisli, but is and `Async -> Async`. it can be changed in the following way:

```js
// fake :: String -> Async String Object
const fake = compose(
  chain(lookup),
  chain(safe(test(/^file-(a|b|c)/))),
  safe(isString)
)
```

**To Reproduce**
1. Copy the `chain` example [from here](https://evilsoft.github.io/crocks/docs/crocks/Async.html#chain) and paste it into your playground of choise
2. Run the example
3. Watch it error.

 [Repl](https://repl.it/@bennypowers/crocks-async-chain-docs-bug) 

**Expected behavior**
The provided example should run without error

**Additional context**

**Comment by dalefrancis88** [comment]
Fixed in https://github.com/evilsoft/crocks/pull/383
