### ISSUE TITLE
Errors should use a consistent voice

### ISSUE THREAD

**Issue by bennypowers** [evilsoft/crocks#404]
**Describe the bug**
Following on https://github.com/evilsoft/crocks/pull/403#discussion_r290143440, all errors should use a :corn:sistent voice, preferring active over passive voices where possible

Good:
"First argument must be a Number" 

Bad:
"Number is required for first argument"

This is also an opportunity to fix capitalization and other grammatical nits in error messages.

**To Reproduce**
Filed as bug since changing errors is a change to API, however there's no repro- it's strings.

**Comment by bennypowers** [comment]
God-willing, I'll soon put together a PR to address this.

**Comment by dalefrancis88** [comment]
This is accepted and understood to be a core goal. Closing the issue
