### ISSUE TITLE
Documentation or example of using Result Crock?

### ISSUE THREAD

**Issue by imranypatel** [evilsoft/crocks#410]
Any help just to get started with Result crock.

**Comment by dalefrancis88** [comment]
Yes, there is a full documentation for the `Result` crock that is very soon going to be released. 

Until it's released you can see the committed version here, https://github.com/evilsoft/crocks/blob/master/docs/src/pages/docs/crocks/Result.md

let us know if you have any further questions on it and feel free to join the [Gitter](https://gitter.im/crocksjs/crocks) we're all quite active on there if you want to discuss

**Comment by dalefrancis88** [comment]
Hey @imranypatel, this documentation has now been released. You can check it out at https://evilsoft.github.io/crocks/docs/crocks/Result.html
