### ISSUE TITLE
Documentation for Identity.ap doesn't work

### ISSUE THREAD

**Issue by devinholloway** [evilsoft/crocks#423]
**Describe the bug**
Documentation code for Indentity.ap doesn't work.

**To Reproduce**
Documentation uses the following code
`
const prod = a => b => a * b
const double = prod(2)

Identity(double)
  .ap(5)
`
which doesn't work when copied and pasted.

**Expected behavior**
Based on the documentation, I think the value 5 also needs to be wrapped in Identity (which also makes the code work)

**Comment by dalefrancis88** [comment]
Thanks for raising that @devinholloway, i'll put a fix in for it now. That should be `Identity(5)`

**Comment by dalefrancis88** [comment]
Thanks again @devinholloway, this has now been merged to master and will be in the next release
