### ISSUE TITLE
Adding in the `compose2`/`binaryCompose` combinator

### ISSUE THREAD

**Issue by dalefrancis88** [evilsoft/crocks#428]
**Feature Request**
Adding in the `compose2`/`binaryCompose` combinator would add some real nice power to the system. I think we could also overload it to support taking a binary array or a `Pair` 

https://hackage.haskell.org/package/util-0.1.13.0/docs/Util.html#v:compose2

**Describe alternatives for how you do this now**
Have it in my local codebase

**Code**
```
const compose2 = f => g => h => x => y => f(g(x))(h(y))
```

**Additional context**

**Comment by evilsoft** [comment]
I am all for the addition of this, just as is, we can think about the Pair/Array application later.

**Comment by dalefrancis88** [comment]
Closing as will be implemented on #431, can continue any discussion there as needed :)
