### ISSUE TITLE
Add Crocks to cdnjs

### ISSUE THREAD

**Issue by DJohn001** [evilsoft/crocks#445]
It wold be nice have Crocks added to cdnjs so that people could get an easy impression and fiddle around with it in like jsfiddle.net or some other online editor with cdnjs support.

**Comment by bennypowers** [comment]
We're planning to release crocks as JavaScript modules (aka es modules) in a future version. That would let you do:

```js
import compose from 'https://unpkg.com/crocks/helpers/compose.js?module';
```

Would that work for you?

**Comment by DJohn001** [comment]
Sorry i'm not very familiar with es modules. What I'm actually trying to do is get the example given in the talk https://www.youtube.com/watch?v=H8DiYOFYQtw working in jsfiddle.net. If you could give me a start with importing for example the "And" function and function from another module, I think I'll figure out the rest by myself.

Thank you for the quick response!

**Comment by evilsoft** [comment]
@DJohn001 those module bits are gonna be 🔥 
But in the mean time does that unkpkg link work for you or your flow?

https://unpkg.com/browse/crocks@0.12.4/index.js will get you the crocks object, or you can get individual files the way @bennypowers shown above.

I will get a PR on cdnjs as we meet there requirements now and keep this issue posted with updates.

**Comment by JohannesBraaksma** [comment]
Hello,

Thank you this works. One other question which may be a little bit off topic but is triggered by the first answer. I'v copied the code below from my node file. When I try to run it it gave me the error:
"SyntaxError: Cannot use import statement outside a module". What does this mean?

`import {and, isNumber} from 'https://unpkg.com/crocks@0.12.4/dist/crocks.min.js';
const gte = a => b =>
	a >= b
  
const validScore = score =>
	and(isNumber, gte(65)) 
  
console.log(validScore(70)(60))`

Kind regards, 
Johannes

**Comment by bennypowers** [comment]
Since that file is a script, not a module, you should not try to import from it.

Instead, destructure the functions you need off the global namespace variable that the `crocks.min.js` script assigns to the `window`

```html
<script src="https://unpkg.com/crocks@0.12.4/dist/crocks.min.js">
<script>
const {and, isNumber} = crocks
const gte = a => b =>
a >= b

const validScore = score =>
and(isNumber, gte(65))

console.log(validScore(70)(60))
</script>
```

**Comment by DJohn001** [comment]
Oke as mentioned in my previous post I changed my question a little bit. I'm now try to get it working in NodeJS it the same way is in the youtube presentation, without downloading the whole package. But it looks like you need to include it in a webpage and run it in the browser.

**Comment by bennypowers** [comment]
Right, since crocks is currently distributed as CommonJS modules (or as a minified browser bundle), when you need to use it in nodejs, use `require`

```
npm install --save crocks
node index.js
```
```js
// index.js
const {and, isNumber} = require('crocks')
const gte = a => b =>
a >= b

const validScore = score =>
and(isNumber, gte(65))

console.log(validScore(70)(60))
```

**Comment by evilsoft** [comment]
@DJohn001 
If you wanna use the same node runner thing that I was using during that preso, you could try this:
https://gitlab.com/evilsoft/evil-playground

Just clone it to your local box and do an `npm install --save crocks` then run `npm start` and you will have the runner going.

**Comment by DJohn001** [comment]
Ok, thanks for the quick support
