### ISSUE TITLE
Incomplete docs

### ISSUE THREAD

**Issue by krzysztofpniak** [evilsoft/crocks#467]
It looks like some ADT's aren't documented, ie. Unit, IO, Writer. Is this library still maintained? I found it really amazing and I'm crossing fingers for it.

**Comment by dalefrancis88** [comment]
Hey @krzysztofpniak I'm glad you've found the package and really like it. it's still actively maintained and we have a `gitter` channel you can use as well to ask questions of the community. The documentation pieces are currently tracked here and in a couple of other issues, https://github.com/evilsoft/crocks/issues/42 @karthikiyengar will likely have `Writer` done by the end of the week

**Comment by dalefrancis88** [comment]
We're always looking for any help if you want you're more than welcome to grab any of the pieces if you're passionate about them or learning them while you document. I know IO is one of the ones i've received questions on recently

**Comment by krzysztofpniak** [comment]
It's good to hear that it is still active. I can try to submit a PR for IO docs. I know how it works.

**Comment by dalefrancis88** [comment]
Nice work, that'd be awesome. I don't use it so it'll be good to have someone write it that can add some real-world context. 

Reach out on the Gitter if you want any questions answered real time while you're doing it

**Comment by karthikiyengar** [comment]
Closing in favour of #379 #378 #377 #376 #375
