### ISSUE TITLE
`getProp` of `null` value returns a `Just`

### ISSUE THREAD

**Issue by dharmavagabond** [evilsoft/crocks#487]
As the title says, having something like `getProp('current')({ current: null })`, returns `Just(null)`, since internally it uses the `isDefined` function—which only checks for `undefined` and not a `null` value.
Is that the intended behavior?

**Comment by dalefrancis88** [comment]
Yes this is the expected behaviour. There are a lot of scenarios where `null` is considered a valid value. If you want to do that you could use kleisli comp with `getProp` and `safe`

```
composeK(
    safe(isNotNull),
    getProp('current')
)
```

**Comment by dharmavagabond** [comment]
Ok, thanks mate.

**Comment by dalefrancis88** [comment]
np, glad to help. If you want, feel free to join the [gitter](https://gitter.im/crocksjs/crocks) if you like. It's quite active

**Comment by dharmavagabond** [comment]
Will do, cheers!
