### ISSUE TITLE
[QUESTION]: ~> syntax, "lifting" functions

### ISSUE THREAD

**Issue by lesar** [evilsoft/crocks#496]
what means ~> using in Hindley Milner signature?  
I have not found it around...  
and what you mean by lift a function?  

best regards,
Leonardo

**Comment by bennypowers** [comment]
That's a modification of HM for JavaScript. it means "method of object"

https://github.com/fantasyland/fantasy-land#type-signature-notation

lifting a function can mean different things

It might, and usually, means wrapping the function in an Applicative instance

https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Applicative.html#v:liftA2

**Comment by lesar** [comment]
thank you very mutch
