### ISSUE TITLE
dimap in arrow

### ISSUE THREAD

**Issue by ftaiolivista** [evilsoft/crocks#498]
Hi.
Would not be nice to implement [dimap](https://typeclasses.com/profunctors#the---profunctor) in arrow?

**Comment by evilsoft** [comment]
We totally have that with `promap` on our profuctors `Star` and `Arrow`.
In the [docs here](https://crocks.dev/docs/crocks/Arrow.html#promap)

In javascript as part of the [Fantasy-Land spec](https://github.com/fantasyland/fantasy-land#profunctor), we use `promap`

**Comment by ftaiolivista** [comment]
Ops, I was missing it. Thank you.
