### ISSUE TITLE
Organization by discrete definitions/specs

### ISSUE THREAD

**Issue by rstegg** [evilsoft/crocks#58]
If crocks will use the common terms of category theory such as Functor, Monoid and Monad, then in order to illustrate the face value of each crock, should there be organization (in the readme, source, or elsewhere) for better API documentation and overall quality?

**Comment by evilsoft** [comment]
Do you have an sample of what you are thinking?

**Comment by evilsoft** [comment]
If you mean mark the containers labels like:

Implements
---
`Setoid`, `Functor`, `Apply`, `Applicative`, `Chain`, `Monad`

Then a page could be made to describe the constraints of each?

I say this is a good idea!!

**Comment by evilsoft** [comment]
One thing I would disagree with is creating a page that lists or organizes (and then links to) specific ADTs.

So this would be Bad News Bears:

Setiod
---
[Maybe](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
[Either](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
[Pair](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
...

**Comment by rstegg** [comment]
Yes! To your second reply;  possibly above the description so it would go,

* `Crock a`

* Implements

* Description/example

* Constructor/instances

* sigs

**Comment by rstegg** [comment]
But also avoiding writing specs or duplicating fantasy-land/[insert spec lib].  

Since interoperability between certain types is key, I think there may be a more soluble answer here so I'll leave this issue open for now until the API is more fleshed out.

**Comment by rstegg** [comment]
Thinking this over, giving breathing room [minimal api] would make for a **better tomorrow**.  I'm going to leave this open for if anyone has more intuitive ideas, but i want to say it's too early to make these guesses.

**Comment by evilsoft** [comment]
I am closing this out. no reason to have this taking up valuable space.
We can revisit later
